### ISSUE TITLE
Request: Can we have Office Code Pro?

### ISSUE THREAD

**Issue by jenhsun** [gabrielelana/awesome-terminal-fonts#10]
I just find out the Modified version of Source Code Pro. https://github.com/nathco/Office-Code-Pro
Can we have that built with awesome terminal fonts? That would be wonderful I think.

**Comment by gabrielelana** [comment]
Sorry, I don't support the patching strategy anymore (too much work, too many issues), but you can:
* Do it yourself, use the scripts in this repository (like: https://github.com/gabrielelana/awesome-terminal-fonts/blob/patching-strategy/sourcecodepro.sh) the main source of burden is to find the "correct" values for `ratio`, `shift-x` and `shift-y` parameters
* Don't use a patched font but use the fallback strategy (if your font engine supports it)

**Comment by jenhsun** [comment]
Dude, thank you for your reply. I don't have any experience on fonts but I will take a look you just suggest.
