### ISSUE TITLE
The font still not working for OSX

### ISSUE THREAD

**Issue by johnWIll17** [gabrielelana/awesome-terminal-fonts#11]
I followed the instruction but nothing happened. I want to use an octicon git-branch. I also use the font `PragmataPro` as my default font in terminal as well as `vim`.

Here is my set up
1. copy 3 fonts from `./build` into `.fonts` directory
2. run `fc-cache -fv ~/.fonts`
3. copy file `./config/10-symbols.conf` to `~/.config/fontconfig/conf.d`

Because I use `PragmataPro` as my font so I leave the config file as it was.
But after did all of these things, nothing happened. I still miss octicon git-branch.

Did I missed?

**Comment by gabrielelana** [comment]
Open a terminal anche execute `echo "\uf20c"` what do you see?

One problem could be that in your system freetype2 is not configured to look in the user's home directory for configuration files under `~/.config`. One possibile solution would be to copy the configuration file in a global directory, probably under `/etc` to see if it works.

Let me know.

**Comment by wladston** [comment]
The title of this issue should change to convey that it doesn't work on Mac OS, but works on Linux.

I spent over 3 hours researching this, tried everything, even changing my DefaultFontFallbacks.plist file with Xcode. It seems Mac OS has its custom way to render fonts, and it looks like it ignores gliphs from private space in its failover mechanism.

**Comment by DFieldFL** [comment]
I am having a problem with the fallback fonts as well on Ubuntu 16.04. I have all the fonts located in ~/.fonts/. Below is my font config `10-symbols.conf`.

```<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
	<alias>
		<family>Source Code Pro</family>
		<prefer>
			<family>Pomodoro</family>
			<family>FontAwesome</family>
			<family>Octicons</family>
			<family>Icomoon</family>
			<family>PowerlineSymbols</family>
		</prefer>
	</alias>
</fontconfig>
```

I have tried the command you suggested `echo "\uf20c"` with this font config in either `~/.config/fontconfig/conf.d/` or `/etc/fonts/conf.d/` and it returns `\uf20c` and not the pretty symbol. I also made sure the default terminal app in Ubuntu has Source Code Pro selected as the font. Any suggests?

**Comment by gabrielelana** [comment]
@DFieldFL try with `echo -e "\uf20c"`

If that doesn't work, can you tell me what terminal are you using? `gnome-terminal`?

**Comment by gabrielelana** [comment]
Seems like OSX is not supporting the fallback strategy, you need to install a patched font, you can find some in [here](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/fonts)

**Comment by DFieldFL** [comment]
@gabrielelana The `-e` option displays the icon. as expected. Is there other step I missed to get this working correctly?

**Comment by gabrielelana** [comment]
@DFieldFL nope, AFAIK now you can use the icons in your prompt or wherever you want in your terminal

**Comment by DFieldFL** [comment]
Thankyou for the help. Looks like I need to update Oh-My-Git to use the correct characters.
