### ISSUE TITLE
Fonts not visible on ubuntu

### ISSUE THREAD

**Issue by ojacquemart** [gabrielelana/awesome-terminal-fonts#15]
Hello,

The fonts are not visible in the terminal configuration (Edit > Profiles > Edit current ...).
I have tried to place the fonts in `~/.fonts/` or `/usr/share/fonts/truetype`.

I followed the instructions from the oh-my-git doc:
```
# Copy the awesome fonts to ~/.fonts
cd /tmp
git clone http://github.com/gabrielelana/awesome-terminal-fonts
cd awesome-terminal-fonts
git checkout patching-strategy
mkdir -p ~/.fonts
cp patched/*.ttf ~/.fonts

# update the font-info cache
sudo fc-cache -fv ~/.fonts
```
Any idea?

**Comment by paulochf** [comment]
+1

I already use the them at work, now I was installing in my PC but then also stumbled in this problem.

**Comment by ojacquemart** [comment]
Thanks, but I gave it a try but I got the same result. I cant' see the fonts in the gnome-terminal settings.

**Comment by paulochf** [comment]
@ojacquemart, can you view the font?

By that I mean, if you double click the font file, you should see the typography in the Font Viewer.

**Comment by ojacquemart** [comment]
Yes, I can view the font and it is marked as installed.

By the way, I installed an another Inconsolata ttf to try (from http://kvz.io/blog/2009/05/25/install-the-best-coding-font/)... and I can choose it in the settings. Finally, I can see the nice icons. I don't really understand why this ttf work and not the one from this repo.

Thanks for your help.

I close the issue. If anynone can try to explain?

**Comment by tnguyen14** [comment]
I'm running into the same problem as @ojacquemart as well. Not sure how to fix it.
