### ISSUE TITLE
Issues with fall back fonts and Yosemite

### ISSUE THREAD

**Issue by smbambling** [gabrielelana/awesome-terminal-fonts#16]
I've followed the directions in the install section but OS X still doesn't seem to honor the fallback font config for freetype

````
echo "\uf20c"

````

Any suggestions on getting this working ?

**Comment by smbambling** [comment]
I loaded all the included Fonts into my local Library as well but still no luck with the translation. 

I do see the fonts lists when using fc-list.

````
fc-list | grep -i awesome
/Users/smbambling/.fonts/fontawesome-regular.ttf: FontAwesome:style=Regular
/Users/smbambling/Library/Fonts/fontawesome-regular.ttf: FontAwesome:style=Regular
````

**Comment by schlessera** [comment]
I have this issue too. Fonts show up in fc-list, but the fallback does not seem to work.
I'm trying to get it working with Source Code Pro on Yosemite.

**Comment by smbambling** [comment]
@schlessera please let me know if you make any headway on  getting this to work with fallback fonts in place of patching.

I've been testing the new [hack](http://sourcefoundry.org/hack/) typeface which looks pretty nice.

**Comment by simonweil** [comment]
I have the same issue.
Fallbacks don't seem to work on OSX.

The only thing I did manage is to install the fonts `open /path/to/font.ttf` and choose it as the non-ascii font in `iTerm2`.
But that isn't very perfect as it can have only 1 fallback font so I miss my powerline fonts...

**Comment by schlessera** [comment]
I gave up on the fallback method and just install the patched font for now. Would love to get this working properly, though.

**Comment by simonweil** [comment]
Where can I download the patched font from?

**Comment by simonweil** [comment]
OK, found them in the other branch, this works :)
