### ISSUE TITLE
Any tips for fonts not showing up in rxvt?

### ISSUE THREAD

**Issue by WishCow** [gabrielelana/awesome-terminal-fonts#17]
I'm using rxvt-unicode, and I can't get the fonts to show up, with the fallback method. I'm trying

```
echo -e "\uf175"
```
But this produces a square in rxvt. If I try it in xfce4-terminal, it works fine.

**Comment by ben-ben** [comment]
It doesn't work because the characters have different widths. You can read about this in `man 7 urxvt` (Section "Why does rxvt-unicode leave pixel droppings"). 
Here someone had the same problem with a different font: https://bbs.archlinux.org/viewtopic.php?id=184089

**Comment by gabrielelana** [comment]
I will consider this closed since the OP hasn't said anything in almost a year
