### ISSUE TITLE
Awesome Powerline Fonts dose not worked

### ISSUE THREAD

**Issue by lanffy** [gabrielelana/awesome-terminal-fonts#18]
this is my .zshrc content:
```
# Path to your oh-my-zsh installation.
# Path to your oh-my-zsh installation.
export ZSH=/Users/rlanffy/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"
DEFAULT_USER=""
POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='flat'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
#POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="↳ "

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"
```

I installed pro like **how to install** as your said.

when the config is **POWERLEVEL9K_MODE='awesome-patched'** and the terminal is like this:
![terminal1](http://7xjh09.com1.z0.glb.clouddn.com/terminal1.png)

when the config is **POWERLEVEL9K_MODE='flat'** and the terminal is like this:

![terminal2](http://7xjh09.com1.z0.glb.clouddn.com/terminal2.png)

**Comment by dritter** [comment]
@lanffy I assume you use the `fallback-strategy`?

The problem arises from different codepoints in fallback- and patching-strategy. In powerlevel9k we use the codepoints for patching-strategy. At that point I didn't know that the codepoints differ, I just propagated patching-strategy, as this is easier to install..

**Comment by lanffy** [comment]
@dritter ,thank you for your answer.
I still do not know how to solve it.
When I close the **POWERLEVEL9K_MODE** config like this:
**#POWERLEVEL9K_MODE='flat'** 
and
**#POWERLEVEL9K_MODE='awesome-patched'** 
the terminal looks like this:
![terminal3](http://7xjh09.com1.z0.glb.clouddn.com/terminal3.png)

how can use terminal like this:
![googTerminal](https://cloud.githubusercontent.com/assets/1544760/7959660/67612918-09fb-11e5-9ef2-2308363c3c51.png)

**Comment by dritter** [comment]
@lanffy Just install the pre-patched fonts from the [patching-stategy branch](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched).

**Comment by lanffy** [comment]
@dritter  thank you very much.
I installed pre-patched what you said.
and set config: **POWERLEVEL9K_MODE='awesome-patched'** 

and the terminal is like this:
![terminal4](http://7xjh09.com1.z0.glb.clouddn.com/terminal4.png)

my iterm2 config is like this:
![terminal5](http://7xjh09.com1.z0.glb.clouddn.com/terminal5.png)

thank you again.

**Comment by dustinmichels** [comment]
How does one install the pre patched fonts from that branch?

**Comment by Guang1234567** [comment]
@all

How to work at osx.

you dont need to do any thing...

just  install the font with suffix `xxx + Awesome.ttf` in https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched

then,  iterm2 -> preference -> text -> font,  select  the `xxx + Awesome.ttf`, that's all.
