### ISSUE TITLE
Patching Font Terminus

### ISSUE THREAD

**Issue by paridin** [gabrielelana/awesome-terminal-fonts#19]
I don't understand how can patch my font.

In the past I patched Terminus as Powerline, but now i want to embed the awesome chars, can you help me to know what is the way to patch with this fonts to my Terminus Powerline.

I reused the code into the droid.sh, and i don't get erros, so I continue with the installation using the FontBook. And I set the font into Iterm2, the problem is not rendered the right chars.

Here my fonts.
[Terminus.ttf](https://mega.nz/#!9oJEVI5Q!LsdsBamiiW1tcLQABe_93_cGr6v5Uc_QtTwo5p7f2XE)
[Terminus-Powerline.ttf](https://mega.nz/#!Z5g3zZ6R!v4WfXHnhx5Bc7LioOITm9UoRX8ahX0NjvhyWPT0T7uo)

**Comment by gabrielelana** [comment]
I no longer use the patch strategy but you can find a patched Terminus with almost the same glyphs [here](https://github.com/ryanoasis/nerd-fonts)
