### ISSUE TITLE
Unable to make the font work on Ubuntu

### ISSUE THREAD

**Issue by cedricmessiant** [gabrielelana/awesome-terminal-fonts#21]
I followed the instructions but it does not seem to work. I'm on Ubuntu 15.10. 

I read https://github.com/gabrielelana/awesome-terminal-fonts/issues/11, I can see the icon if I enter `echo "\uf20c"` in a terminal. I tried to move `10-symbols.conf` to `/etc/fonts/conf.d/` with no success

**Comment by gabrielelana** [comment]
If you see the icon with `echo "\uf20c"` then it worked, you can have symbols in your terminal

What do you mean with "it doesn't seem to work"? What are you trying to accomplish?

**Comment by cedricmessiant** [comment]
Thanks for your quick answer ! I try to make the fonts work with https://github.com/bhilburn/powerlevel9k So my problem is probably there. Gonna investigate on that ! I close this issue
