### ISSUE TITLE
Can't get it to work on OSX

### ISSUE THREAD

**Issue by jottr** [gabrielelana/awesome-terminal-fonts#22]
This is what I am doing: 

```
$ which fc-cache
/usr/local/bin/fc-cache

$ git clone https://github.com/gabrielelana/awesome-terminal-fonts.git
$ cd awesome-terminal-fonts

$ ./install.sh

$ ls ~/.fonts
devicons-regular.sh
devicons-regular.ttf
fontawesome-regular.sh
fontawesome-regular.ttf
octicons-regular.sh
octicons-regular.ttf
pomicons-regular.sh
pomicons-regular.ttf
```
I have **iTerm2** set up to use `Meslo LG M Regular for Powerline`, so I made `~/.config/fontconfig/conf.d/10-symbols.conf` look accordingly:

```

<fontconfig>
  <alias>
    <family>Meslo LG M Regular for Powerline</family>
    <prefer>
      <family>Pomodoro</family>
      <family>FontAwesome</family>
      <family>Octicons</family>
      <family>Icomoon</family>
    </prefer>
  </alias>
</fontconfig>

```

Let's check if `fc-list` sees `Meslo LG M Regular for Powerline`:

```
$ fc-list | grep 'Meslo LG M Regular for Powerline'

/Users/jottr/Library/Fonts/Meslo LG M Regular for Powerline.otf: Meslo LG M for Powerline:style=RegularForPowerline

```

Let's check if `fc-list` sees `pomicons-regular`:

```
$ fc-list | grep Pomodoro
/Users/jottr/.fonts/pomicons-regular.ttf: Pomodoro:style=Regular

```

Let's check if anything from `~/.fonts/fontawesome-regular.sh` is available in the shell:

```
$ echo '\uf00c'

```
Nope. Nothing.
Running `./build.sh` first does not help either.

Also, a cursory check seems to indicate that some symbols, i.e. [fa-hourglass](https://fortawesome.github.io/Font-Awesome/icon/hourglass/) seem to be missing from `fontawesome-regular.sh`.

------
```
iTerm2 Build 2.9.20160206

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.0.0)

```

**Comment by wadkar** [comment]
I am having similar issues. Any work around? What can I do to help resolve this issue?

**Comment by stackcats** [comment]
I have the same issue.

**Comment by nymona** [comment]
I'm having this issue on OSX, though no problems on linux. Possible solution for @jottr: 

The 10-symbols.conf should be structured like: 

<fontconfig>
  <alias>
      <family>FontAwesome</family>
    <prefer>
      <family>Pomodoro</family>
      <family>Octicons</family>
      <family>Icomoon</family>
      <family>PragmataPro</family>
    </prefer>
  </alias>
</fontconfig>

**Comment by gabrielelana** [comment]
Seems like OSX is not supporting the fallback strategy, you need to install a patched font, you can find some in [here](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/fonts)
