### ISSUE TITLE
Add font-linux

### ISSUE THREAD

**Issue by polarathene** [gabrielelana/awesome-terminal-fonts#23]
https://github.com/Lukas-W/font-linux

Alternatives to the penguin glyph would be nice :)

---

Probably not the right place, but few questions.

I came across this [SourceCodePro + Powerline + Awesome Regular](https://github.com/stefano-meschiari/dotemacs/blob/master/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf) font, it seems to be custom patch by the user. Would you know if the `Awesome` bit was referring to this repo or Font Awesome?

With the fallback strategy, is the only benefit this repo provides a font map? I noticed some of the fonts haven't been updated in a while like with other repo's. Rendering wise, if fallback works would be effectively the same as having those glyphs patched together as a single font or are there potential differences? 

OSX doesn't seem to support the fallback option from what I'm reading, and some terminals/OS have rendering issues where I assume fallback strategy won't be enough? Besides adding the glyphs to merge into a base font, how much work/time can be involved to fix those offset/size issues I've seen around the place? These official patched versions seem quite outdated: https://github.com/powerline/fonts , not sure how much that matters.

**Comment by gabrielelana** [comment]
@polarathene sorry for the huge delay

> Alternatives to the penguin glyph would be nice :)

I will consider it :-)

>  Would you know if the Awesome bit was referring to this repo or Font Awesome?

I think the font is taken from [this repo](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched), in this case Awesome means that it includes Font Awesome

> With the fallback strategy, is the only benefit this repo provides a font map? 

* Font maps
* Sensible font relocation to avoid clashing (aka multiple fonts using the same codepoint) and the usage of codepoints already defined by the UNICODE standard
* Instructions on how to make it work

> Rendering wise, if fallback works would be effectively the same as having those glyphs patched together as a single font or are there potential differences?

A huge difference: every font has it's own metrics (geometric data), in particular all glyphs of a monospace fonts need to have the same bounding box, so when you patch a monospace font with a non monospace one (all icon fonts are not monospaced) you need to calculate the bounding box of the base monospaced font and then resize all glyphs of the icon font accordingly. In theory it's all good, in practice it's a mess and it requires many manual adjustments. The same job is done by the font engine with the fallback strategy and IMHO the final result is better.

> OSX doesn't seem to support the fallback option from what I'm reading, and some terminals/OS have rendering issues where I assume fallback strategy won't be enough?

Yes sometimes the patching strategy is the only option, this is why I kept around my [old branch](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy), if you want you can fiddle around with the [patch script](https://github.com/gabrielelana/awesome-terminal-fonts/blob/patching-strategy/patch) I've  made
