### ISSUE TITLE
.fonts not a directory

### ISSUE THREAD

**Issue by svpersteve** [gabrielelana/awesome-terminal-fonts#24]
I'm getting the above error when trying to "copy all the fonts from ./build directory to ~/.fonts directory"

**Comment by gabrielelana** [comment]
Try to run the command `ls -l ~/.fonts`, what's the output?

What's your OS? If it's Linux, what Linux distribution?

As an easy fix try to create the directory with `mkdir ~/.fonts`

**Comment by svpersteve** [comment]
Thanks for replying so quickly 😃 

This is the response: 
`-rw-r--r--  1 stephenbrewer  staff  80652 27 Jun 16:54 /Users/stephenbrewer/.fonts`

I tried making the directory but a file already exists called .fonts and it doesn't seem to let me.

**Comment by gabrielelana** [comment]
I see, you are using OSX, I don't know who uses that file or what it contains, anyway I wouldn't touch it 😄 

On OSX there's a simpler way

1 - Download the patched fonts from https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched (the *.ttf files)
2 - Open the application "Font Book" (installed by default on OSX)
3 - Menu "File > Add Fonts" and select all the downloaded files

Now you have the fonts with the icon glyphs installed on your system. You can used them in your terminal configuring the preferences

Note: the instructions are meant mostly for Linux (it can work also on OSX but it's not a clean solution) I must make that explicit in the README
