### ISSUE TITLE
please use release system

### ISSUE THREAD

**Issue by shibumi** [gabrielelana/awesome-terminal-fonts#25]
Hello,
It would be awesome if you could use the release system. I am working on a package for Arch Linux.
So that everybody can install your fonts more easier.

Thanks!

**Comment by gabrielelana** [comment]
@shibumi That would be awesome! 😉

**Comment by shibumi** [comment]
@gabrielelana Yes but therefore I need a static release. So please could you please use the release system?

Just click on releases and then make a release with a version like for example: 1.0

![release](https://paste.archlinux.de/wz5G/)

**Comment by gabrielelana** [comment]
Sorry, I did not understand the first message 😝 

Ok, just a clarification: do you want to create a package for the default fallback strategy or for the patch strategy (where you use a font made of a normal font + the icon fonts)?

**Comment by shibumi** [comment]
I have already a git-based package.
I just copy all your files in ./build/ into /usr/share/fonts and i copy your 10-symbols.conf in /etc/fonts/conf.avail/ Thats all what I do. 

Just make a release of it. a release is nothing more than a tag for a specific commit.
So for example your git HEAD will have the tag version 1.0 or something. 

With a release version I can just get a tar.gz file of your archive instead of git cloning everytime everything.

**Comment by gabrielelana** [comment]
Done

**Comment by shibumi** [comment]
Thanks! I will close this issue and post the link here to the new package if done.
