### ISSUE TITLE
Consider adding OS X instructions

### ISSUE THREAD

**Issue by leoj3n** [gabrielelana/awesome-terminal-fonts#27]
If https://github.com/gabrielelana/awesome-terminal-fonts/issues/7#issuecomment-236417688 works for more than just me; it would probably we worth adding to the README.

**Comment by gabrielelana** [comment]
@leoj3n: Wow, nice work! Thanks! Since it's so detailed I'm thinking to put it in a wiki page, what do you think?

**Comment by leoj3n** [comment]
https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X

**Comment by gabrielelana** [comment]
Thanks! ❤️
