### ISSUE TITLE
macOS Sierra can't display font.

### ISSUE THREAD

**Issue by al03** [gabrielelana/awesome-terminal-fonts#30]
After update my Mac to macOS Sierra, the font in iTerm2 can't display anymore.
In `Font Book`, the `fontawesome` can't display right too.
<img width="705" alt="screen shot 2016-09-21 at 3 50 48 pm" src="https://cloud.githubusercontent.com/assets/1445425/18702201/30018938-8013-11e6-815a-81c2de15db6a.png">

**Comment by rhblind** [comment]
Same here..

**Comment by millisami** [comment]
Me too on macOS Sierra.
When I try to install the patched fonts, the validation fails with 1 error, no proper message shown.
And those patched fonts dates back to 3 yrs ago.
It would be better to rebuild it again with macOS Sierra support.

**Comment by HamedGh** [comment]
Same Problem

**Comment by mingrammer** [comment]
Same here

**Comment by steakknife** [comment]
This is not a real issue. It's not a end-user font. It contains glyphs which are added to other fonts, usually monospaced.

**Comment by alexchernokun** [comment]
I failed to use this font in iTerm+oh-my-zsh. Could you help me with it?
<img width="456" alt="screen shot 2016-12-08 at 20 13 36" src="https://cloud.githubusercontent.com/assets/21589637/21021830/f1cc44c0-bd82-11e6-86b7-5d097059116b.png">
<img width="1030" alt="screen shot 2016-12-08 at 20 14 57" src="https://cloud.githubusercontent.com/assets/21589637/21021854/055d12a8-bd83-11e6-8402-2182706371e3.png">

**Comment by haidaraM** [comment]
@alexchernokun you need to change also the **Non-ASCII Font** in order to correctly display the font.

**Comment by alexchernokun** [comment]
@haidaraM Thank you!

**Comment by seagle0128** [comment]
same issue here. please fix it. Thanks!

**Comment by PDDStudio** [comment]
It's working fine for me on Sierra. Did you update your fallback fonts?

**Comment by al03** [comment]
![screen shot 2017-01-23 at 11 21 49 am](https://cloud.githubusercontent.com/assets/1445425/22190436/2cf39bd0-e15e-11e6-9110-c53329d1222e.png)
<img width="325" alt="screen shot 2017-01-23 at 11 21 44 am" src="https://cloud.githubusercontent.com/assets/1445425/22190437/2d2f9cca-e15e-11e6-8577-6e4b1ad93b49.png">

Am I config right? The fonts in Font Book is fine, but still not working at iTerm.

**Comment by carlsmith** [comment]
Everything works perfectly for me, using Terminal on Sierra, and using the installation instructions linked to in the README. I know the issue mentions iTerm2, but the title suggests a general issue with Sierra.

**Comment by MathiasSM** [comment]
@haidaraM did the trick. Set both ascii and non-ascii fonts the same and iTerm will understand

**Comment by tjtrabue** [comment]
I had the same problem when trying to use these fonts with the amazing Powerlevel9k ZSH theme, but it turned out much to my chagrin that I just didn't read all of the installation instructions for Powerlevel9k. You have to paste this line into your `~/.zshrc` ***above*** the line specifying your `ZSH_THEME`:
```
POWERLEVEL9K_MODE='awesome-fontconfig'
```
Once I added this line and restarted iTerm2, everything worked just fine. Hope this helps!

**Comment by danieltoro** [comment]
How can I set 3 fonts? SourceCodePro+Powerline+Awesome Regular at 14pt. Anyone can help me, please

**Comment by al03** [comment]
@danieltoro Why 3 fonts? iTerm only support 2 font to set. 
![screen shot 2017-08-29 at 6 10 33 pm](https://user-images.githubusercontent.com/1445425/29816080-665965a2-8ce5-11e7-87d8-0e3119aec480.png)
