### ISSUE TITLE
SourceCodePro+Powerline+Awesome Not working in Chrome 55 on Win10

### ISSUE THREAD

**Issue by n3il-a** [gabrielelana/awesome-terminal-fonts#32]
I'm trying to use the fonts with Secure Shell in Chrome, and they're not displaying properly.  At first I thought it was my installation/method of usage, but after setting my mono-spaced font to SourceCodePro+Powerline+Awesome in the Chrome preferences, I'm beginning to think this is a Chrome incompatibility.

It displays fine in the preferences preview:
![snip1](https://cloud.githubusercontent.com/assets/2353329/21889838/e3886d4a-d898-11e6-8fd8-0f633817c735.PNG)
But when it comes to actually displaying text on a page, it fails:
![snip2](https://cloud.githubusercontent.com/assets/2353329/21889839/e3888c4e-d898-11e6-98c6-2f839904e4a0.PNG)

If this is a Chrome issue, then so be it, but other iterations of SouceCodePro work without an issue in hterm (Secure Shell), so I'm not 100% sure where the problem lies.  If there's anything else I should try, let me know.

**Comment by gabrielelana** [comment]
I don't know if you still have this issue but I bet you have better chances at overriding the CSS classes of Secure Shell in Chrome that make the patched font work. The patched font is kind of an hack for situations where you cannot use multiple fonts at once. Browsers supports the usage of multiple fonts and with [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=it) you can customize the appearence of Secure Shell, you can inject a CSS rule that forces the browser to display a certain range of codepoints with a specified font

```css
@font-face {
    font-family: Foobar;
    src: local('Times New Roman');
    unicode-range: U+61-6E;
}
```
