### ISSUE TITLE
Availability of other fonts

### ISSUE THREAD

**Issue by flrgsr** [gabrielelana/awesome-terminal-fonts#33]
Hi,

I would like to use e.g the "Menlo Regular for Powerline" in combination with the awesome fonts.
As far as I understand I would need to patch these myself? 
Is there a a simply way to do this?

**Comment by jep-dev** [comment]
This project uses FontForge, which has some pretty good documentation [here](http://designwithfontforge.com/en-US/index.html). I haven't used it myself.

**Comment by gabrielelana** [comment]
@flrgsr You can look in the `patching-strategy` branch for some script
