### ISSUE TITLE
Fonts not working on zsh themes

### ISSUE THREAD

**Issue by evenme** [gabrielelana/awesome-terminal-fonts#35]
I installed the fonts as described (fallback strategy), used antigen for oh-my-zsh, oh-my-git and themes) but still haven't got the fonts working, even though I can see the characters when using echo.

![screenshot from 2017-02-08 11-36-41](https://cloud.githubusercontent.com/assets/117922/22746740/dec65776-edf2-11e6-91bb-613c6afd16fa.png)

I'm using CentOS and RedHat on that (tested on multiple servers).

**Comment by gabrielelana** [comment]
I guess this is more an issue of `oh-my-git` than the fonts, try to open an issue on `oh-my-git` referring this
