### ISSUE TITLE
MIssing "python" (snake) icon

### ISSUE THREAD

**Issue by diraol** [gabrielelana/awesome-terminal-fonts#38]
If you can, please add a Python (Snake) icon ;) [would fix this for `awesome-terminal-fonts` users -
 https://github.com/bhilburn/powerlevel9k/issues/338]

**Comment by DjMoren** [comment]
@diraol, I'm in the same scenario, but I think that the problem here is that the Snake icon is not in [Font-Awesome](http://fontawesome.io/icons/) (actually v4.7) 
Maybe @gabrielelana can confirm this...

**Comment by davidmpaz** [comment]
Making a search on FA for python give no result for python. I did create a request for that [#11098](https://github.com/FortAwesome/Font-Awesome/issues/11098)

**Comment by DjMoren** [comment]
Meanwhile, if you came to this issue from powerlevel9k icons, you can set the code _\ue63c_ (real python icon) instead of _\U1F40D_ in _icons.zsh_ file to see the real python icon served by devicons

**Comment by gabrielelana** [comment]
Actually the Python glyph it's already included in the `devicons` font, as @DjMoren wrote it's on `\ue63c`. To make things easier and more stable anyone should always use variables to refer to glyphs and not codepoints (like `\ue63c`). With the last commit, after sourcing the devicons font map (`source ~/.fonts/devicons-regular.sh`) you can print the Python glyph with `echo "\u$CODEPOINT_OF_DEVICONS_PYTHON"`
