### ISSUE TITLE
[Question] Name of the font

### ISSUE THREAD

**Issue by ajitid** [gabrielelana/awesome-terminal-fonts#45]
What is the name of Source Code Pro Powerline Awesome font (patched one)? I want to use it my editor (VS Code), in which I had to type the name of the font to use it, but I am not able to get its right name. :-/

**Comment by gabrielelana** [comment]
Maybe I don't understand the question but the original font is [SourceCodePro](https://github.com/powerline/fonts/tree/master/SourceCodePro). Is this the answer you were looking for?

**Comment by ajitid** [comment]
I used Hack instead.
