### ISSUE TITLE
So it's still impossible to get a job right now

### ISSUE THREAD

**Issue by xavierXing** [gabrielelana/awesome-terminal-fonts#48]
I installed this font, and I set it, but the icon shows "? "This looks like this   

I feel that you are in the configuration, writing very vague, resulting in many people installation is not successful... I hope you see this feedback. You can maintain your documents. To help more people use it

**Comment by gabrielelana** [comment]
Unfortunately there isn't a straightforward way for all system to configure it successfully. If you are willing to provide more feedback (OS, font engine, terminal type/version, ecc...) maybe we can spot what's wrong and later improve the documentation
