### ISSUE TITLE
How much of the setup instructions are relevant to arch linux?

### ISSUE THREAD

**Issue by InfiniteCoder** [gabrielelana/awesome-terminal-fonts#51]
Arch Linux has this in it's repo, so does Manjaro. I'm using Manjaro, and I installed the package. I am able to use the fonts. But I was confused regarding what part of the the installation instructions I need to follow. Also the directories change, so I had to make some minor changes to commands.

1. Fonts are in `/usr/share/fonts/awesome-terminal-fonts`. Looks like the package copies them here.
2. `.sh` files already present in above directory
3. rebooted instead of fc-cache command. Didn't try it
4. config is in `/etc/fonts/conf.d/10-symbols.conf`. Replaced font to `Hack` using root permissions. (I guess this was unnecessary, I should have copied and made change only to local file)
5. copied the above configuration file to `~/.config/fontconfig/conf.d`, had to create that directory first.
6. Added source command to zsh and bash rc files.

I guess I did it right, still wanted to verify. Also, is there any specific powerline theme that makes use of these icons? How does one make use of these icons?

**Comment by gabrielelana** [comment]
Hi @InfiniteCoder I don't really know what Arch/Manjaro packages are doing, I'm not the maintainer so I cannot comment on that, IMHO the package should be self contained and independent. @shibumi can you comment on that?

>  is there any specific powerline theme that makes use of these icons?

Look at https://github.com/bhilburn/powerlevel9k or https://github.com/arialdomartini/oh-my-git

**Comment by shibumi** [comment]
Hello,
My `/etc/fonts/conf.d/10-symbols.conf` looks like this:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<!--
When a glyph is missing in the current font freetype2 will look into
other installed fonts to see if it's going to find it, but which fonts?
and in which order?

The configuration below aim to declare an ordered list of fonts
to be looked into when a glyph is not found in a specic font

<alias>
  <family>FONT_WITH_A_POSSIBLY_MISSING_GLYPH</family>
  <prefer>
    <family>FIRST_FONT_TO_LOOK_INTO</family>
    <family>SECOND_FONT_TO_LOOK_INTO</family>
    <family>...</family>
  </prefer>
</alias>
-->

<fontconfig>
  <alias>
    <family>PragmataPro</family>
    <prefer>
      <family>Pomodoro</family>
      <family>FontAwesome</family>
      <family>Octicons</family>
      <family>Icomoon</family>
    </prefer>
  </alias>
</fontconfig>
```

that works pretty well. So no idea whats not working at your side. Sadly you use manjaro. So I have no idea if manjaro devs don't change the package / patch additional features / whatever..

**Comment by InfiniteCoder** [comment]
I guess I only needed to change to font name, the rest was probably unnecessary. Although it might make sense to create local config as the changes in base config file would get overwritten with each update.

**Comment by kqvanity** [comment]
@InfiniteCoder Where exactly did you change it?
@shibumi I've installed your package and have Source Code pro in my alacritty toml file. The glyphs still don't render correctly. Am I missing on something
