### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fbourigault** [gabrielelana/awesome-terminal-fonts#8]
What is the license of your project ? And what are the fronts licenses provided in the fonts directory ?

It could also be nice to reference those fonts in the README.md

Regards,
Fabien

**Comment by gabrielelana** [comment]
Thanks, you are right and sorry for the delay, somehow it slipped my attention. 17b1c42ad6d64032adbf51b074801b66865c9ece, f5e25ef23b6b81d8418d68b8ec6e05e0f2fc85d7 and a0d3413b9c543cfee7b81c57644815a5a3e21410 should fix this issue
