### ISSUE TITLE
brew install fc-cache -> fc-cache is not more available?

### ISSUE THREAD

**Issue by heyalbert** [gabrielelana/awesome-terminal-fonts#9]
brew install fc-cache
Error: No available formula for fc-cache
Searching formulae...
Searching taps...

**Comment by corelon** [comment]
I have fc-cache installed but the whole process does not work
I even tried installing the fonts in ~/Library/Fonts which is the default "home" fonts directory still nothing. I can see the fonts in Font Book, the configuration though does not work

**Comment by dritter** [comment]
:+1:  Same for me. Fortunately there is the branch `patching-strategy`, which contains some patched fonts. Have a look at [here](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched). @corelon @heyalbert

**Comment by gabrielelana** [comment]
@corelon @heyalbert @dritter Have a look at #7, if you find a solution let me know or better, send me a pull request :wink:

**Comment by corelon** [comment]
Thank @gabrielelana I have found several links from the one you sent. I need to find some time to try. In the meantime would it be possible to include some examples of use like the one you show in the screenshots? 
Thanks again.

**Comment by gabrielelana** [comment]
I need to find the time :smile: in the meanwhile, if you want, my dotfiles are public https://github.com/gabrielelana/dotfiles

**Comment by bibaijin** [comment]
"brew install fontconfig" works

**Comment by gabrielelana** [comment]
Fixed with #13
